services:
  backend:
    build:
      args:
        NODE_ENV: test
        
    environment:
      NODE_ENV: test
      POSTGRES_TEST_DB: test_database
      POSTGRES_TEST_USER: test_user
      POSTGRES_TEST_PASSWORD: test_password
      POSTGRES_TEST_HOST: postgres
      POSTGRES_TEST_PORT: 5432
    command: /bin/sh -c "sleep 1 && npm run migrate && sleep 1 && npm test"
    volumes:
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    depends_on:
      - postgres

  postgres:
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    

volumes:
  postgres-data-test:
  test-results:
  coverage: