version: '3.8'
services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5434:5432"

  postgres_test:
    image: "postgres"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5435:5432"

volumes:
  postgres-data:
  postgres-test-data:
