services:
  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    build:
      target: development
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:8000/api/v1

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      DB_HOST: postgres
      DB_PORT: 5432
    command: /bin/sh -c "npm run migrate && npx nodemon server.js"

  postgres:
    ports:
      - "5435:5432"
