services:
  frontend:
    ports:
      - "8000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      NODE_ENV: development

  backend:
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      DB_HOST: postgres
      DB_PORT: 5432
    command: /bin/sh -c "npx nodemon server.js"

  postgres:
    ports:
      - "5435:5432"
