services:
  nginx:
    image: nginx:1.24.0-bullseye
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c "npm run migrate && node server.js"

  postgres:
    image: "postgres:16.2-bullseye"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
